path = "wanda.scon";
arm = disarm_import(disarm_env_file(path));
mesh = disarm_mesh_create();
anim = "Test";
scale = 1;
offsetX = room_width / 2;
offsetY = room_height / 2;
animationBlend = 0;
animationSpeed = 0.01;
debugOverlay = false;
//show_debug_overlay(true);
//disarm_skin_add(arm, "Test Map");